# Generated by Django 5.1.6 on 2025-02-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_age_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='img')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
