# Generated by Django 5.1.6 on 2025-02-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_discount_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='price_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(max_length=100)),
            ],
        ),
    ]
