# Generated by Django 5.1.6 on 2025-03-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
    ]
