# Generated by Django 5.1.6 on 2025-03-11 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
    ]
