# Generated by Django 5.1.6 on 2025-03-18 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_order_razorpay_orderid_order_razorpay_paymentid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ord_product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Processing', 'Processing'), ('Packaged', 'Packaged'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Cancelled', 'Cancelled')], default='Order Placed', max_length=100),
        ),
        migrations.CreateModel(
            name='order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order')),
                ('ord_product', models.CharField(default='', max_length=1000)),
                ('quantity', models.CharField(max_length=5)),
                ('price', models.IntegerField()),
                ('total', models.CharField(default='', max_length=100)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
    ]
